using System;

namespace SimplyWallSt.Listing.Repository.CompanyScore
{
    /// <summary>
    /// An object with various scores for the company
    /// </summary>
    public class CompanyScore
    {
        /// <summary>
        /// Id of the company score. Generated by database
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Company's unique identifier
        /// </summary>
        public Guid CompanyId { get; set; }

        /// <summary>
        /// Date when the row was created in source database
        /// </summary>
        public DateTime DateGenerated { get; set; }

        /// <summary>
        /// Score for the company's dividend payouts
        /// </summary>
        public int Dividend { get; set; }

        /// <summary>
        /// Score for the company's future
        /// </summary>
        public int Future { get; set; }

        /// <summary>
        /// Score for the company's health
        /// </summary>
        public int Health { get; set; }

        /// <summary>
        /// Score for the company's management
        /// </summary>
        public int Management { get; set; }

        /// <summary>
        /// Score for the company's past
        /// </summary>
        public int Past { get; set; }

        /// <summary>
        /// Score for the company's valuation
        /// </summary>
        public int Value { get; set; }

        /// <summary>
        /// Miscellaneous score for the company
        /// </summary>
        public int Misc { get; set; }

        /// <summary>
        /// Total score for the company
        /// </summary>
        public int Total { get; set; }

        /// <summary>
        /// A sentence describing the performance of the company
        /// </summary>
        public string Sentence { get; set; }
    }
}
